import { Photo, User } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Professional photographer specializing in portraits and landscapes',
    followers: ['user2', 'user3'],
    following: ['user2'],
  },
  {
    id: 'user2',
    name: 'Mike Chen',
    email: 'mike@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    bio: 'Food and travel photographer',
    followers: ['user1', 'user3', 'user4'],
    following: ['user1', 'user3'],
  },
  {
    id: 'user3',
    name: 'Emma Davis',
    email: 'emma@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    bio: 'Wedding and lifestyle photography',
    followers: ['user1', 'user2'],
    following: ['user1', 'user2', 'user4'],
  },
  {
    id: 'user4',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    bio: 'Street and fashion photographer based in NYC',
    followers: ['user2'],
    following: ['user3'],
  },
];

export const mockPhotos: Photo[] = [
  {
    id: '1',
    imageUrl: 'https://images.unsplash.com/photo-1544124094-8aea0374da93?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3J0cmFpdCUyMHBob3RvZ3JhcGh5fGVufDF8fHx8MTc2Mjk2ODQ3MXww&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Golden Hour Portrait',
    description: 'Beautiful portrait captured during golden hour',
    userId: 'user1',
    userName: 'Sarah Johnson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    likes: 124,
    likedBy: [],
    comments: [
      {
        id: 'c1',
        userId: 'user2',
        userName: 'Mike Chen',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
        text: 'Stunning composition!',
        createdAt: '2025-11-10T10:30:00Z',
      },
    ],
    createdAt: '2025-11-09T14:20:00Z',
    category: 'Portrait',
  },
  {
    id: '2',
    imageUrl: 'https://images.unsplash.com/photo-1729944080510-16b8a89df8b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYW5kc2NhcGUlMjBtb3VudGFpbiUyMHBob3RvZ3JhcGh5fGVufDF8fHx8MTc2Mjk3NTQ2MHww&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Mountain Majesty',
    description: 'Epic mountain landscape at sunrise',
    userId: 'user2',
    userName: 'Mike Chen',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    likes: 89,
    likedBy: [],
    comments: [],
    createdAt: '2025-11-08T08:15:00Z',
    category: 'Landscape',
  },
  {
    id: '3',
    imageUrl: 'https://images.unsplash.com/photo-1533091090875-1ff4acc497dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWRkaW5nJTIwcGhvdG9ncmFwaHl8ZW58MXx8fHwxNzYzMDM3MTkxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Wedding Bliss',
    description: 'Capturing love on their special day',
    userId: 'user3',
    userName: 'Emma Davis',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    likes: 256,
    likedBy: [],
    comments: [],
    createdAt: '2025-11-07T16:45:00Z',
    category: 'Wedding',
  },
  {
    id: '4',
    imageUrl: 'https://images.unsplash.com/photo-1617657172340-15a0fabc3605?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaG90b2dyYXBoeSUyMGFydHxlbnwxfHx8fDE3NjMwNjc5Nzd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Abstract Shadows',
    description: 'Playing with light and shadow',
    userId: 'user1',
    userName: 'Sarah Johnson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    likes: 67,
    likedBy: [],
    comments: [],
    createdAt: '2025-11-06T12:30:00Z',
    category: 'Abstract',
  },
  {
    id: '5',
    imageUrl: 'https://images.unsplash.com/photo-1628803184377-c5167a0cb6fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXQlMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NjMwMjcyNjB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Urban Life',
    description: 'Street photography in the city',
    userId: 'user4',
    userName: 'Alex Rivera',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    likes: 142,
    likedBy: [],
    comments: [],
    createdAt: '2025-11-05T09:20:00Z',
    category: 'Street',
  },
  {
    id: '6',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb29kJTIwcGhvdG9ncmFwaHl8ZW58MXx8fHwxNzYzMDMzNTkyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Culinary Art',
    description: 'Food photography at its finest',
    userId: 'user2',
    userName: 'Mike Chen',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    likes: 198,
    likedBy: [],
    comments: [],
    createdAt: '2025-11-04T15:10:00Z',
    category: 'Food',
  },
  {
    id: '7',
    imageUrl: 'https://images.unsplash.com/photo-1622746908635-b825a84939e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcmNoaXRlY3R1cmUlMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NjI5ODUwNDN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Architectural Wonder',
    description: 'Modern architecture beauty',
    userId: 'user3',
    userName: 'Emma Davis',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    likes: 103,
    likedBy: [],
    comments: [],
    createdAt: '2025-11-03T11:40:00Z',
    category: 'Architecture',
  },
  {
    id: '8',
    imageUrl: 'https://images.unsplash.com/photo-1704208316515-a32f81e373ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwcGhvdG9ncmFwaHl8ZW58MXx8fHwxNzYyOTkwNTA1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Fashion Forward',
    description: 'Contemporary fashion photography',
    userId: 'user4',
    userName: 'Alex Rivera',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    likes: 215,
    likedBy: [],
    comments: [],
    createdAt: '2025-11-02T13:25:00Z',
    category: 'Fashion',
  },
  {
    id: '9',
    imageUrl: 'https://images.unsplash.com/photo-1489396160836-2c99c977e970?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0cmF2ZWwlMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NjI5NzY5OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Wanderlust',
    description: 'Travel photography from around the world',
    userId: 'user1',
    userName: 'Sarah Johnson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    likes: 178,
    likedBy: [],
    comments: [],
    createdAt: '2025-11-01T10:00:00Z',
    category: 'Travel',
  },
  {
    id: '10',
    imageUrl: 'https://images.unsplash.com/photo-1626354338145-96a3f13c0e62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjB3aWxkbGlmZSUyMHBob3RvZ3JhcGh5fGVufDF8fHx8MTc2MzA2Nzc0Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Wild Nature',
    description: 'Wildlife in its natural habitat',
    userId: 'user2',
    userName: 'Mike Chen',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    likes: 234,
    likedBy: [],
    comments: [],
    createdAt: '2025-10-31T14:50:00Z',
    category: 'Wildlife',
  },
  {
    id: '11',
    imageUrl: 'https://images.unsplash.com/photo-1565660467558-2cc40ad3066b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMHBob3RvZ3JhcGh5fGVufDF8fHx8MTc2MzAxOTExMXww&ixlib=rb-4.1.0&q=80&w=1080',
    title: 'Color Burst',
    description: 'Abstract color photography',
    userId: 'user3',
    userName: 'Emma Davis',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    likes: 91,
    likedBy: [],
    comments: [],
    createdAt: '2025-10-30T16:20:00Z',
    category: 'Abstract',
  },
];
